### ISSUE TITLE
Make sure api spec is up to date.

### ISSUE THREAD

**Issue by oed** [uport-project/3box-hash-server#8]
Currently the [api spec](https://github.com/uport-project/3box-hash-server/blob/master/SPECIFICATION.md) is not up to date with how the hash-server actually works. We should update it so that it reflects the actual code.

We should also investigate if we can come up with a process to ensure that the spec is always in parity with the code. Maybe we can autogenerate this doc somehow?

**Comment by ozlemulusoy** [comment]
No more relevant.
